USE sakila;
-- 1 List the number of films per category.

SELECT category.name AS cat_name, COUNT(film_category.film_id) AS numbers_films
FROM category
INNER JOIN film_category ON category.category_id = film_category.category_id -- category.category_id and film_category.category_id
GROUP BY cat_name
ORDER BY numbers_films DESC;

-- 2 Retrieve the store ID, city, and country for each store.

SELECT s.store_id, ci.city, co.country
FROM store s
INNER JOIN address AS a ON s.address_id = a.address_id
INNER JOIN city AS ci ON a.city_id = ci.city_id
INNER JOIN country AS co ON ci.country_id = co.country_id;


-- 3 Calculate the total revenue generated by each store in dollars.

SELECT st.store_id, SUM(p.amount) AS total_revenue
FROM payment p
JOIN staff AS s ON p.staff_id = s.staff_id
JOIN store AS st ON s.store_id = st.store_id
GROUP BY st.store_id
ORDER BY total_revenue DESC;

-- 4 Determine the average running time of films for each category.

SELECT c.name AS category, AVG(f.length) AS avg_length
FROM film AS f
JOIN film_category AS fc ON f.film_id = fc.film_id
JOIN category AS c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY avg_length DESC;